name: solidtest
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.19
flutter:
  uses-material-design: true
